# Generated by Django 5.1.1 on 2024-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('morning_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evening_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_spaces', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
