# Generated by Django 5.1.1 on 2024-09-08 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='morning_fee',
            new_name='fee',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='current_spaces',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='evening_fee',
        ),
        migrations.AddField(
            model_name='parking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
