# Generated by Django 5.1.1 on 2024-09-08 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_morning_fee_parking_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity_available', models.PositiveIntegerField(default=0)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.parking')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.schedule')),
            ],
        ),
    ]
