# Generated by Django 5.1.1 on 2024-09-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_schedule_parking_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking_schedule',
            old_name='horario',
            new_name='schedule',
        ),
    ]
