# Generated by Django 5.1.1 on 2024-09-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_rename_parking_schedule_parkingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingschedule',
            name='capacity_available',
        ),
    ]
