# Generated by Django 5.1.1 on 2024-09-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_parkingschedule_capacity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingschedule',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
