# Generated by Django 5.1.1 on 2024-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_parkingschedule_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
