# Generated by Django 5.1.1 on 2024-09-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_parking_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='actualCapacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
