# Generated by Django 5.1.1 on 2024-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_remove_parkingschedule_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='actualCapacity',
        ),
        migrations.AddField(
            model_name='parkingschedule',
            name='actualCapacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
