# Generated by Django 5.1.1 on 2024-09-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_remove_parking_actualcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='extra_fee_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
