# Generated by Django 5.1.1 on 2024-09-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_parking_extra_fee_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='extra_fee_per_hour',
        ),
    ]
