# Generated by Django 5.1.1 on 2024-09-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='vehiculo',
            new_name='vehicles',
        ),
    ]
