# Generated by Django 5.1.1 on 2024-09-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_vehiculo_client_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='taxId',
            new_name='indentification',
        ),
    ]
