# Generated by Django 5.1.1 on 2024-09-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_states_client_state_alter_vehicle_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10),
        ),
    ]
