# Generated by Django 5.1.1 on 2024-09-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_vehicle_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
