# Generated by Django 5.1.1 on 2024-09-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, default='password', max_length=128, null=True),
        ),
    ]
