# Generated by Django 5.1.1 on 2024-09-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_reservation_client'),
        ('customer', '0013_alter_vehicle_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
