# Generated by Django 5.1.1 on 2024-09-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
