# Generated by Django 5.1.1 on 2024-09-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
