# Generated by Django 5.1.1 on 2024-09-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('customer', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.parking'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.vehicle'),
        ),
    ]
