# Generated by Django 5.1.1 on 2024-09-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='state_payment',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('P', 'Payed'), ('A', 'Active'), ('C', 'Cancel')], default='A', max_length=1),
        ),
    ]
