# Generated by Django 5.1.1 on 2024-09-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_reservation_state_payment_and_more'),
        ('customer', '0003_rename_taxid_client_indentification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customer.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fechaHoraFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
