# Generated by Django 5.1.1 on 2024-09-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_reservation_client_and_more'),
        ('customer', '0009_alter_vehicle_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customer.client'),
        ),
    ]
