# Generated by Django 5.1.1 on 2024-09-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
    ]
