# Generated by Django 5.1.1 on 2024-09-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_reservation_client'),
        ('organization', '0008_parking_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='fechaHoraFin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='fechaHoraInicio',
        ),
        migrations.AddField(
            model_name='reservation',
            name='parkingSchedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.parkingschedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
